"""empty message

Revision ID: 0118a3c341cc
Revises: 39148a4d41bf
Create Date: 2023-11-19 20:30:01.630577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0118a3c341cc'
down_revision = '39148a4d41bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.drop_column('aditional_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aditional_info', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
