"""empty message

Revision ID: 42da57f5d114
Revises: d1efe03a867e
Create Date: 2023-11-02 01:08:46.903022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42da57f5d114'
down_revision = 'd1efe03a867e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Apellido', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.drop_column('Apellido')

    # ### end Alembic commands ###
