"""empty message

Revision ID: 78846dd8f697
Revises: 9133aac4b482
Create Date: 2023-11-01 21:04:21.732550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78846dd8f697'
down_revision = '9133aac4b482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.drop_constraint('administrator_position_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.create_unique_constraint('administrator_position_key', ['position'])

    # ### end Alembic commands ###
