"""empty message

Revision ID: 9133aac4b482
Revises: ac92ed2ad61c
Create Date: 2023-11-01 16:38:35.355477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9133aac4b482'
down_revision = 'ac92ed2ad61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('aditional_info', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('position')
    )
    op.drop_table('admon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('fecha_nacimiento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('correo_electronico', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('cargo', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('contraseña', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('informacion_adicional', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admon_pkey'),
    sa.UniqueConstraint('cargo', name='admon_cargo_key'),
    sa.UniqueConstraint('correo_electronico', name='admon_correo_electronico_key'),
    sa.UniqueConstraint('informacion_adicional', name='admon_informacion_adicional_key')
    )
    op.drop_table('administrator')
    # ### end Alembic commands ###
