"""empty message

Revision ID: 99d65165ec17
Revises: 6aaae4471762
Create Date: 2023-10-28 01:59:52.878597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d65165ec17'
down_revision = '6aaae4471762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('correo_electronico', sa.String(length=120), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=False),
    sa.Column('contraseña', sa.String(length=10), nullable=False),
    sa.Column('informacion_adicional', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cargo'),
    sa.UniqueConstraint('correo_electronico'),
    sa.UniqueConstraint('informacion_adicional')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administrador')
    # ### end Alembic commands ###
