"""empty message

Revision ID: ac92ed2ad61c
Revises: 99d65165ec17
Create Date: 2023-10-28 02:05:38.241763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac92ed2ad61c'
down_revision = '99d65165ec17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('correo_electronico', sa.String(length=120), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=False),
    sa.Column('contraseña', sa.String(length=10), nullable=False),
    sa.Column('informacion_adicional', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cargo'),
    sa.UniqueConstraint('correo_electronico'),
    sa.UniqueConstraint('informacion_adicional')
    )
    op.drop_table('administrador')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('fecha_nacimiento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('correo_electronico', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('cargo', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('contraseña', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('informacion_adicional', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='administrador_pkey'),
    sa.UniqueConstraint('cargo', name='administrador_cargo_key'),
    sa.UniqueConstraint('correo_electronico', name='administrador_correo_electronico_key'),
    sa.UniqueConstraint('informacion_adicional', name='administrador_informacion_adicional_key')
    )
    op.drop_table('admon')
    # ### end Alembic commands ###
