"""empty message

Revision ID: d1efe03a867e
Revises: 6164b4a645b6
Create Date: 2023-11-02 01:06:42.807306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1efe03a867e'
down_revision = '6164b4a645b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
