"""empty message

Revision ID: fbdd22ba8e28
Revises: 42da57f5d114
Create Date: 2023-11-02 01:11:11.040451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbdd22ba8e28'
down_revision = '42da57f5d114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.String(length=120), nullable=True))
        batch_op.drop_column('Apellido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Apellido', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###
